pipeline {

   agent {
      label 'OCPNonProdAgent'
   }
   
   environment{
      NAMESPACE = 'ais-liberty-support'
      BUILD_NUMBER = "${env.BUILD_NUMBER}" 
      APP_BUILD_PATH = "${WORKSPACE}/jenkins-deploy"
   }
    stages {
    
   stage('deploy liberty application') {
       steps {
         script {
			  dir("${APP_BUILD_PATH}"){   				
				echo'--- kustomization.yaml'
				sh 'cat kustomization.yaml \n'
            	sh "oc kustomize ./"
            }
		 }
       }
    }       
  } 
  post {
         // Clean after build
         always {
            echo 'Cleaning up after build...'
             cleanWs(cleanWhenNotBuilt: false,
                     deleteDirs: true,
                     disableDeferredWipeout: true,
                     notFailBuild: true,
                     patterns: [[pattern: '.gitignore', type: 'INCLUDE'],
                                [pattern: '.propsfile', type: 'EXCLUDE']])
         }
     }
}
