apiVersion: liberty.websphere.ibm.com/v1
kind: WebSphereLibertyApplication
metadata:
  name: test-liberty-app
  namespace: ais-liberty-support
spec:
  license:
    accept: true
    edition: IBM WebSphere Application Server
    productEntitlementSource: IBM Cloud Pak for Applications Advanced
  expose: true
  resources: {}
  route:
    termination: passthrough
  applicationImage: 'image-registry.openshift-image-registry.svc:5000/ais-liberty-support/test-liberty-app:1.0'
  service:
    certificateSecretRef: lib-demo-secret
    port: 9443
    type: ClusterIP
  manageTLS: true
  pullPolicy: IfNotPresent
  serviceAccount:
    mountToken: true
  replicas: 1
  applicationName: test-liberty-app